### ISSUE TITLE
TSC2007 Kernel Setup

### ISSUE THREAD

**Issue by liosab** [osandov/raspi#1]
Hello,
I follow up yourTSC2007 kernel module set-up

 from begging to the end and I had some errors during compiling the TSC2007 module.
Below showing the errors.
Could help me to solve them ?
I am a beginner in raspi and linux. I am a hardware engineer.

Thanks in advance
Regards
liosab

First error :
pi@raspberrypi ~/TSC2007 $ make
make -C /lib/modules/3.10.25+/build M=/home/pi/TSC2007 modules
make[1]: entrant dans le répertoire « /usr/src/kernels/3.10.25+ »
  CC [M]  /home/pi/TSC2007/tsc2007.o
/home/pi/TSC2007/tsc2007.c:277:22: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘tsc2007_probe’
/home/pi/TSC2007/tsc2007.c:375:22: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘tsc2007_remove’
/home/pi/TSC2007/tsc2007.c:407:12: error: ‘tsc2007_probe’ undeclared here (not in a function)
/home/pi/TSC2007/tsc2007.c:408:2: error: implicit declaration of function ‘__devexit_p’ [-Werror=implicit-function-declaration]
/home/pi/TSC2007/tsc2007.c:408:25: error: ‘tsc2007_remove’ undeclared here (not in a function)
/home/pi/TSC2007/tsc2007.c:167:20: warning: ‘tsc2007_soft_irq’ defined but not used [-Wunused-function]
/home/pi/TSC2007/tsc2007.c:227:20: warning: ‘tsc2007_hard_irq’ defined but not used [-Wunused-function]
/home/pi/TSC2007/tsc2007.c:249:12: warning: ‘tsc2007_open’ defined but not used [-Wunused-function]
/home/pi/TSC2007/tsc2007.c:269:13: warning: ‘tsc2007_close’ defined but not used [-Wunused-function]
cc1: some warnings being treated as errors
make[2]: **\* [/home/pi/TSC2007/tsc2007.o] Erreur 1
make[1]: **\* [_module_/home/pi/TSC2007] Erreur 2
make[1]: quittant le répertoire « /usr/src/kernels/3.10.25+ »
make: **\* [all] Erreur 2
pi@raspberrypi ~/TSC2007 $ 

Second Error :
When I replace :
/\* LSA
static int __devexit tsc2007_remove(struct i2c_client *client)
*/

by :
static int tsc2007_remove(struct i2c_client *client)

and :

/\* LSA
static int __devinit tsc2007_probe(struct i2c_client *client,
                   const struct i2c_device_id *id)
*/

by:
static int tsc2007_probe(struct i2c_client *client,
                   const struct i2c_device_id *id)

and :
.remove     = tsc2007_remove /_LSA __devexit_p(tsc2007_remove)_/,

The compil is working fine :
pi@raspberrypi ~/TSC2007 $ make
make -C /lib/modules/3.10.25+/build M=/home/pi/TSC2007 modules
make[1]: entrant dans le répertoire « /usr/src/kernels/3.10.25+ »
  CC [M]  /home/pi/TSC2007/tsc2007.o
  Building modules, stage 2.
  MODPOST 2 modules
  LD [M]  /home/pi/TSC2007/tsc2007.ko
make[1]: quittant le répertoire « /usr/src/kernels/3.10.25+ »
pi@raspberrypi ~/TSC2007 $ 

pi@raspberrypi ~/TSC2007 $ sudo make install 
mkdir -p /lib/modules/3.10.25+/kernel/drivers/input/touchscreen
cp tsc2007.ko /lib/modules/3.10.25+/kernel/drivers/input/touchscreen/tsc2007.ko
cp tsc_raspi.ko /lib/modules/3.10.25+/kernel/drivers/input/touchscreen/tsc_raspi.ko
sed -i '/blacklist i2c-bcm2708/s/^b/#b/' /etc/modprobe.d/raspi-blacklist.conf
grep -q "i2c-dev" /etc/modules || echo "i2c-dev" | tee -a /etc/modules
grep -q "tsc_raspi" /etc/modules || echo "tsc_raspi" | tee -a /etc/modules
grep -q "tsc2007" /etc/modules || echo "tsc2007" | tee -a /etc/modules
depmod -a
pi@raspberrypi ~/TSC2007 $ 

But the next problem is when I execute :
pi@raspberrypi ~/TSC2007 $ sudo modprobe tsc_raspi
ERROR: could not insert 'tsc_raspi': Exec format error
pi@raspberrypi ~/TSC2007 $ sudo modprobe tsc2007
ERROR: could not insert 'tsc2007': Exec format error
pi@raspberrypi ~/TSC2007 $

**Comment by osandov** [comment]
Hey, sorry for the delay. Looks like the Linux kernel removed the __dev macros at around 3.8, and newer images of Raspbian run 3.10 or 3.12. I grabbed the updated source from upstream and updated the README. I fixed the compilation errors, but I don't have the hardware available to me anymore so I couldn't test it. Let me know if there are any other issues.

**Comment by liosab** [comment]
Hello Omar,

Thanks for your support. I follow your updated readme, and now the TSC files complied and also included in kernel and boot. I had just a blocking during the tsc compilation due to the folder was not accessible in normal user. Then I do it in super user.

Now I don’t have any error on boot and the calibrator recognize the board.

The new issue is the cursor is not moving when I press the screen.

I saw in the topic : http://www.raspberrypi.org/forums/viewtopic.php?f=91 http://www.raspberrypi.org/forums/viewtopic.php?f=91&t=64414&start=50 &t=64414&start=50

That Xof have found some modification to do in the code. I already di it excepted 
- sudo insmod tsc_raspi with penirq_pin=4 (this could be the default one...)
- use WiringPi's gpio(1) to control the pull-up (should be done in the tsc_raspi module but I don't know how yet)

Which I don’t know how to do them.

Regards

Lionel
