### ISSUE TITLE
#include <linux/i2c/tsc2007.h> not found

### ISSUE THREAD

**Issue by Zacharyprime** [osandov/raspi#2]
After running make it throws an error saying the file linux/i2c/tsc2007.h does not exist.
The error gets thrown at: raspi/tsc2007/tsc2007.c:28:10

I feel like if I had that file I wouldn't be needing this repository.

It seems like the tsc2007 driver should just be inside the linux kernel itself (it exists in torvalds/linux).
But the pi doesn't seem to have that part of the kernel installed.

Where can I get this file?

**Comment by Zacharyprime** [comment]
I tried putting the file taken from the linux kernel and putting it into raspi/tsc2007 and then changing the include to be an relative reference ("" instead of <>) to the file.

That causes a host of reference errors, which leads me to believe that the file it wants is probably a modified version of the one in the linux kernel.

**Comment by Zacharyprime** [comment]
I should probably add that I am on a Pi 3B running raspberry pi OS lite

**Comment by osandov** [comment]
This repository is super old so I wouldn't expect it to work anymore. I no longer have the hardware to get this working again. I suspect that you'll want to build the tsc2007 module from the Rasperry Pi kernel source and set it up with device tree.

**Comment by Zacharyprime** [comment]
I understand, the software I'm tasked to maintain that needs this is pretty outdated too, which is the source of the headache...
